// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: p2p.proto

package p2ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	statepb "thomasd/internal/pb/statepb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteType int32

const (
	VoteType_PREVOTE   VoteType = 0
	VoteType_PRECOMMIT VoteType = 1
)

// Enum value maps for VoteType.
var (
	VoteType_name = map[int32]string{
		0: "PREVOTE",
		1: "PRECOMMIT",
	}
	VoteType_value = map[string]int32{
		"PREVOTE":   0,
		"PRECOMMIT": 1,
	}
)

func (x VoteType) Enum() *VoteType {
	p := new(VoteType)
	*p = x
	return p
}

func (x VoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_enumTypes[0].Descriptor()
}

func (VoteType) Type() protoreflect.EnumType {
	return &file_p2p_proto_enumTypes[0]
}

func (x VoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteType.Descriptor instead.
func (VoteType) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

type NodeHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Head          []byte                 `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHello) Reset() {
	*x = NodeHello{}
	mi := &file_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHello) ProtoMessage() {}

func (x *NodeHello) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHello.ProtoReflect.Descriptor instead.
func (*NodeHello) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *NodeHello) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeHello) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *NodeHello) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

type TxBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBroadcast) Reset() {
	*x = TxBroadcast{}
	mi := &file_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBroadcast) ProtoMessage() {}

func (x *TxBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBroadcast.ProtoReflect.Descriptor instead.
func (*TxBroadcast) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *TxBroadcast) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *TxBroadcast) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// NewBlock broadcasts the signed Eternity header alongside its commit proof.
type NewBlock struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Header        *statepb.EternityHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Commit        *statepb.Commit         `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	TxHashes      [][]byte                `protobuf:"bytes,3,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"` // optional hint for downstream nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewBlock) Reset() {
	*x = NewBlock{}
	mi := &file_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlock) ProtoMessage() {}

func (x *NewBlock) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlock.ProtoReflect.Descriptor instead.
func (*NewBlock) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *NewBlock) GetHeader() *statepb.EternityHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NewBlock) GetCommit() *statepb.Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *NewBlock) GetTxHashes() [][]byte {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VoteType               `protobuf:"varint,1,opt,name=type,proto3,enum=thomas.p2p.VoteType" json:"type,omitempty"`
	BlockId       []byte                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Voter         string                 `protobuf:"bytes,3,opt,name=voter,proto3" json:"voter,omitempty"`
	Round         uint64                 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Sig           []byte                 `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *Vote) GetType() VoteType {
	if x != nil {
		return x.Type
	}
	return VoteType_PREVOTE
}

func (x *Vote) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *Vote) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *Vote) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Vote) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type StateSyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSyncReq) Reset() {
	*x = StateSyncReq{}
	mi := &file_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSyncReq) ProtoMessage() {}

func (x *StateSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSyncReq.ProtoReflect.Descriptor instead.
func (*StateSyncReq) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *StateSyncReq) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type StateSyncResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Chunk         [][]byte               `protobuf:"bytes,2,rep,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSyncResp) Reset() {
	*x = StateSyncResp{}
	mi := &file_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSyncResp) ProtoMessage() {}

func (x *StateSyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSyncResp.ProtoReflect.Descriptor instead.
func (*StateSyncResp) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *StateSyncResp) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *StateSyncResp) GetChunk() [][]byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type AnchorCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TxRoot        []byte                 `protobuf:"bytes,4,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`
	Sig           []byte                 `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorCommit) Reset() {
	*x = AnchorCommit{}
	mi := &file_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorCommit) ProtoMessage() {}

func (x *AnchorCommit) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorCommit.ProtoReflect.Descriptor instead.
func (*AnchorCommit) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *AnchorCommit) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *AnchorCommit) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AnchorCommit) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *AnchorCommit) GetTxRoot() []byte {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

func (x *AnchorCommit) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_p2p_proto protoreflect.FileDescriptor

const file_p2p_proto_rawDesc = "" +
	"\n" +
	"\tp2p.proto\x12\n" +
	"thomas.p2p\x1a\vstate.proto\"G\n" +
	"\tNodeHello\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04head\x18\x03 \x01(\fR\x04head\"1\n" +
	"\vTxBroadcast\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\x8b\x01\n" +
	"\bNewBlock\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1c.thomas.state.EternityHeaderR\x06header\x12,\n" +
	"\x06commit\x18\x02 \x01(\v2\x14.thomas.state.CommitR\x06commit\x12\x1b\n" +
	"\ttx_hashes\x18\x03 \x03(\fR\btxHashes\"\x89\x01\n" +
	"\x04Vote\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.thomas.p2p.VoteTypeR\x04type\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\fR\ablockId\x12\x14\n" +
	"\x05voter\x18\x03 \x01(\tR\x05voter\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x04R\x05round\x12\x10\n" +
	"\x03sig\x18\x05 \x01(\fR\x03sig\"&\n" +
	"\fStateSyncReq\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"A\n" +
	"\rStateSyncResp\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\x12\x14\n" +
	"\x05chunk\x18\x02 \x03(\fR\x05chunk\"\x8b\x01\n" +
	"\fAnchorCommit\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x1d\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_root\x18\x04 \x01(\fR\x06txRoot\x12\x10\n" +
	"\x03sig\x18\x05 \x01(\fR\x03sig*&\n" +
	"\bVoteType\x12\v\n" +
	"\aPREVOTE\x10\x00\x12\r\n" +
	"\tPRECOMMIT\x10\x01B\x1bZ\x19thomasd/internal/pb/p2ppbb\x06proto3"

var (
	file_p2p_proto_rawDescOnce sync.Once
	file_p2p_proto_rawDescData []byte
)

func file_p2p_proto_rawDescGZIP() []byte {
	file_p2p_proto_rawDescOnce.Do(func() {
		file_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)))
	})
	return file_p2p_proto_rawDescData
}

var file_p2p_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_p2p_proto_goTypes = []any{
	(VoteType)(0),                  // 0: thomas.p2p.VoteType
	(*NodeHello)(nil),              // 1: thomas.p2p.NodeHello
	(*TxBroadcast)(nil),            // 2: thomas.p2p.TxBroadcast
	(*NewBlock)(nil),               // 3: thomas.p2p.NewBlock
	(*Vote)(nil),                   // 4: thomas.p2p.Vote
	(*StateSyncReq)(nil),           // 5: thomas.p2p.StateSyncReq
	(*StateSyncResp)(nil),          // 6: thomas.p2p.StateSyncResp
	(*AnchorCommit)(nil),           // 7: thomas.p2p.AnchorCommit
	(*statepb.EternityHeader)(nil), // 8: thomas.state.EternityHeader
	(*statepb.Commit)(nil),         // 9: thomas.state.Commit
}
var file_p2p_proto_depIdxs = []int32{
	8, // 0: thomas.p2p.NewBlock.header:type_name -> thomas.state.EternityHeader
	9, // 1: thomas.p2p.NewBlock.commit:type_name -> thomas.state.Commit
	0, // 2: thomas.p2p.Vote.type:type_name -> thomas.p2p.VoteType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_p2p_proto_init() }
func file_p2p_proto_init() {
	if File_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_goTypes,
		DependencyIndexes: file_p2p_proto_depIdxs,
		EnumInfos:         file_p2p_proto_enumTypes,
		MessageInfos:      file_p2p_proto_msgTypes,
	}.Build()
	File_p2p_proto = out.File
	file_p2p_proto_goTypes = nil
	file_p2p_proto_depIdxs = nil
}
