// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: state.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Legacy ThomasChain header/body (kept for backwards compatibility).
type BlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix seconds
	PrevHash      []byte                 `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TxRoot        []byte                 `protobuf:"bytes,5,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`
	Proposer      []byte                 `protobuf:"bytes,6,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Sig           []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *BlockHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *BlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlockHeader) GetTxRoot() []byte {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

func (x *BlockHeader) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *BlockHeader) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type BlockBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHashes      [][]byte               `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"` // hashes only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBody) Reset() {
	*x = BlockBody{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBody) ProtoMessage() {}

func (x *BlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBody.ProtoReflect.Descriptor instead.
func (*BlockBody) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *BlockBody) GetTxHashes() [][]byte {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body          *BlockBody             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetBody() *BlockBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// EternityHeader captures the canonical proposal metadata that is signed by the
// proposer each round. The signature itself is stored in the parent Commit.
type EternityHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         uint32                 `protobuf:"fixed32,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // "ETER"
	Height          uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round           uint32                 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // unix seconds
	PrevHash        []byte                 `protobuf:"bytes,5,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`                         // 32 bytes
	StateRoot       []byte                 `protobuf:"bytes,6,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`                      // 32 bytes (BLAKE3)
	TxRoot          []byte                 `protobuf:"bytes,7,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`                               // 32 bytes (BLAKE3)
	EvidenceRoot    []byte                 `protobuf:"bytes,8,opt,name=evidence_root,json=evidenceRoot,proto3" json:"evidence_root,omitempty"`             // 32 bytes (default zero)
	ProposerKey     []byte                 `protobuf:"bytes,9,opt,name=proposer_key,json=proposerKey,proto3" json:"proposer_key,omitempty"`                // ed25519 pubkey (32 bytes)
	ProposerSetHash []byte                 `protobuf:"bytes,10,opt,name=proposer_set_hash,json=proposerSetHash,proto3" json:"proposer_set_hash,omitempty"` // 32 bytes merkle root of validator set
	CommitHash      []byte                 `protobuf:"bytes,11,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`                  // 32 bytes hash of prev round commit
	Flags           uint32                 `protobuf:"varint,12,opt,name=flags,proto3" json:"flags,omitempty"`                                             // reserved bitfield
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EternityHeader) Reset() {
	*x = EternityHeader{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EternityHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EternityHeader) ProtoMessage() {}

func (x *EternityHeader) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EternityHeader.ProtoReflect.Descriptor instead.
func (*EternityHeader) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *EternityHeader) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *EternityHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EternityHeader) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *EternityHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EternityHeader) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *EternityHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *EternityHeader) GetTxRoot() []byte {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

func (x *EternityHeader) GetEvidenceRoot() []byte {
	if x != nil {
		return x.EvidenceRoot
	}
	return nil
}

func (x *EternityHeader) GetProposerKey() []byte {
	if x != nil {
		return x.ProposerKey
	}
	return nil
}

func (x *EternityHeader) GetProposerSetHash() []byte {
	if x != nil {
		return x.ProposerSetHash
	}
	return nil
}

func (x *EternityHeader) GetCommitHash() []byte {
	if x != nil {
		return x.CommitHash
	}
	return nil
}

func (x *EternityHeader) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// CommitSig references a single validator vote inside a Commit.
type CommitSig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ValidatorIndex uint32                 `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	PubKey         []byte                 `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`    // ed25519 pubkey
	Step           uint32                 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`                     // 0=proposal,1=prevote,2=precommit
	BlockId        []byte                 `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"` // hash of CanonicalHeaderBytes(header)
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`            // ed25519 signature
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitSig) Reset() {
	*x = CommitSig{}
	mi := &file_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSig) ProtoMessage() {}

func (x *CommitSig) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSig.ProtoReflect.Descriptor instead.
func (*CommitSig) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *CommitSig) GetValidatorIndex() uint32 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *CommitSig) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *CommitSig) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *CommitSig) GetBlockId() []byte {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *CommitSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Commit aggregates all validator signatures for a given height/round.
type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round         uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Signatures    []*CommitSig           `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *Commit) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Commit) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Commit) GetSignatures() []*CommitSig {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// TxProof verifies inclusion of a transaction hash inside tx_root.
type TxProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        []byte                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Siblings      [][]byte               `protobuf:"bytes,2,rep,name=siblings,proto3" json:"siblings,omitempty"`             // ordered path siblings (32 bytes each)
	Directions    []uint32               `protobuf:"varint,3,rep,packed,name=directions,proto3" json:"directions,omitempty"` // 0=left,1=right per level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxProof) Reset() {
	*x = TxProof{}
	mi := &file_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxProof) ProtoMessage() {}

func (x *TxProof) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxProof.ProtoReflect.Descriptor instead.
func (*TxProof) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *TxProof) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *TxProof) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *TxProof) GetDirections() []uint32 {
	if x != nil {
		return x.Directions
	}
	return nil
}

// StateProof verifies a key/value pair inside the prefixed state trie.
type StateProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Siblings      [][]byte               `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	Directions    []uint32               `protobuf:"varint,4,rep,packed,name=directions,proto3" json:"directions,omitempty"`
	Version       []byte                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"` // optional version/epoch tag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateProof) Reset() {
	*x = StateProof{}
	mi := &file_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateProof) ProtoMessage() {}

func (x *StateProof) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateProof.ProtoReflect.Descriptor instead.
func (*StateProof) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *StateProof) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StateProof) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StateProof) GetSiblings() [][]byte {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *StateProof) GetDirections() []uint32 {
	if x != nil {
		return x.Directions
	}
	return nil
}

func (x *StateProof) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

type EpochRewardSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ENet          uint64                 `protobuf:"varint,2,opt,name=e_net,json=eNet,proto3" json:"e_net,omitempty"` // microTHO
	Base          uint64                 `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`
	Bonus         uint64                 `protobuf:"varint,4,opt,name=bonus,proto3" json:"bonus,omitempty"`
	Consensus     uint64                 `protobuf:"varint,5,opt,name=consensus,proto3" json:"consensus,omitempty"`
	NetworkBase   uint64                 `protobuf:"varint,6,opt,name=network_base,json=networkBase,proto3" json:"network_base,omitempty"`
	Foundation    uint64                 `protobuf:"varint,7,opt,name=foundation,proto3" json:"foundation,omitempty"`
	Exchange      uint64                 `protobuf:"varint,8,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochRewardSummary) Reset() {
	*x = EpochRewardSummary{}
	mi := &file_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochRewardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochRewardSummary) ProtoMessage() {}

func (x *EpochRewardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochRewardSummary.ProtoReflect.Descriptor instead.
func (*EpochRewardSummary) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{8}
}

func (x *EpochRewardSummary) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochRewardSummary) GetENet() uint64 {
	if x != nil {
		return x.ENet
	}
	return 0
}

func (x *EpochRewardSummary) GetBase() uint64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *EpochRewardSummary) GetBonus() uint64 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *EpochRewardSummary) GetConsensus() uint64 {
	if x != nil {
		return x.Consensus
	}
	return 0
}

func (x *EpochRewardSummary) GetNetworkBase() uint64 {
	if x != nil {
		return x.NetworkBase
	}
	return 0
}

func (x *EpochRewardSummary) GetFoundation() uint64 {
	if x != nil {
		return x.Foundation
	}
	return 0
}

func (x *EpochRewardSummary) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\fthomas.state\"\xc6\x01\n" +
	"\vBlockHeader\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tprev_hash\x18\x03 \x01(\fR\bprevHash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_root\x18\x05 \x01(\fR\x06txRoot\x12\x1a\n" +
	"\bproposer\x18\x06 \x01(\fR\bproposer\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sig\"(\n" +
	"\tBlockBody\x12\x1b\n" +
	"\ttx_hashes\x18\x01 \x03(\fR\btxHashes\"g\n" +
	"\x05Block\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.thomas.state.BlockHeaderR\x06header\x12+\n" +
	"\x04body\x18\x02 \x01(\v2\x17.thomas.state.BlockBodyR\x04body\"\xf7\x02\n" +
	"\x0eEternityHeader\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\aR\achainId\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x14\n" +
	"\x05round\x18\x03 \x01(\rR\x05round\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tprev_hash\x18\x05 \x01(\fR\bprevHash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x06 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_root\x18\a \x01(\fR\x06txRoot\x12#\n" +
	"\revidence_root\x18\b \x01(\fR\fevidenceRoot\x12!\n" +
	"\fproposer_key\x18\t \x01(\fR\vproposerKey\x12*\n" +
	"\x11proposer_set_hash\x18\n" +
	" \x01(\fR\x0fproposerSetHash\x12\x1f\n" +
	"\vcommit_hash\x18\v \x01(\fR\n" +
	"commitHash\x12\x14\n" +
	"\x05flags\x18\f \x01(\rR\x05flags\"\x9a\x01\n" +
	"\tCommitSig\x12'\n" +
	"\x0fvalidator_index\x18\x01 \x01(\rR\x0evalidatorIndex\x12\x17\n" +
	"\apub_key\x18\x02 \x01(\fR\x06pubKey\x12\x12\n" +
	"\x04step\x18\x03 \x01(\rR\x04step\x12\x19\n" +
	"\bblock_id\x18\x04 \x01(\fR\ablockId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"o\n" +
	"\x06Commit\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x127\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v2\x17.thomas.state.CommitSigR\n" +
	"signatures\"^\n" +
	"\aTxProof\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x12\x1a\n" +
	"\bsiblings\x18\x02 \x03(\fR\bsiblings\x12\x1e\n" +
	"\n" +
	"directions\x18\x03 \x03(\rR\n" +
	"directions\"\x8a\x01\n" +
	"\n" +
	"StateProof\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\bsiblings\x18\x03 \x03(\fR\bsiblings\x12\x1e\n" +
	"\n" +
	"directions\x18\x04 \x03(\rR\n" +
	"directions\x12\x18\n" +
	"\aversion\x18\x05 \x01(\fR\aversion\"\xe6\x01\n" +
	"\x12EpochRewardSummary\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x13\n" +
	"\x05e_net\x18\x02 \x01(\x04R\x04eNet\x12\x12\n" +
	"\x04base\x18\x03 \x01(\x04R\x04base\x12\x14\n" +
	"\x05bonus\x18\x04 \x01(\x04R\x05bonus\x12\x1c\n" +
	"\tconsensus\x18\x05 \x01(\x04R\tconsensus\x12!\n" +
	"\fnetwork_base\x18\x06 \x01(\x04R\vnetworkBase\x12\x1e\n" +
	"\n" +
	"foundation\x18\a \x01(\x04R\n" +
	"foundation\x12\x1a\n" +
	"\bexchange\x18\b \x01(\x04R\bexchangeB\x1dZ\x1bthomasd/internal/pb/statepbb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_state_proto_goTypes = []any{
	(*BlockHeader)(nil),        // 0: thomas.state.BlockHeader
	(*BlockBody)(nil),          // 1: thomas.state.BlockBody
	(*Block)(nil),              // 2: thomas.state.Block
	(*EternityHeader)(nil),     // 3: thomas.state.EternityHeader
	(*CommitSig)(nil),          // 4: thomas.state.CommitSig
	(*Commit)(nil),             // 5: thomas.state.Commit
	(*TxProof)(nil),            // 6: thomas.state.TxProof
	(*StateProof)(nil),         // 7: thomas.state.StateProof
	(*EpochRewardSummary)(nil), // 8: thomas.state.EpochRewardSummary
}
var file_state_proto_depIdxs = []int32{
	0, // 0: thomas.state.Block.header:type_name -> thomas.state.BlockHeader
	1, // 1: thomas.state.Block.body:type_name -> thomas.state.BlockBody
	4, // 2: thomas.state.Commit.signatures:type_name -> thomas.state.CommitSig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
