name: ci
on:
  push: { branches: [ main ], tags: [ "v*" ] }
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true
      - name: Go mod download
        run: go mod tidy && go mod download
      - name: Build
        run: go build -v -tags "cbor blake3" ./cmd/thomasd
      - name: Unit tests
        run: go test -v ./... -count=1
