name: release

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (optional, e.g. v0.1.3)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos:   [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true
      - name: Go mod download
        run: go mod tidy && go mod download
      - name: Build and package
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          REL="thomasd_${{ matrix.goos }}_${{ matrix.goarch }}"
          BIN="thomasd"
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN="thomasd.exe"
          mkdir -p "dist/$REL"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -v -tags "cbor blake3" -o "dist/$REL/$BIN" ./cmd/thomasd
          pushd dist >/dev/null
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            zip -r "${REL}.zip" "$REL"
          else
            tar -czf "${REL}.tar.gz" "$REL"
          fi
          sha256sum "${REL}."* >> checksums.txt
          popd >/dev/null
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            dist/*.zip
            dist/*.tar.gz
            dist/checksums.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Gather assets
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p upload
          shopt -s nullglob
          cp dist/*.zip upload/ 2>/dev/null || true
          cp dist/*.tar.gz upload/ 2>/dev/null || true
          if ls dist/checksums.txt >/dev/null 2>&1; then
            cat dist/checksums.txt > upload/checksums.txt
          else
            cat dist/*checksums*.txt > upload/checksums.txt || true
          fi
          ls -al upload
          test "$(ls -1 upload | wc -l)" -gt 0
      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: ${{ github.event.inputs.tag || github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            upload/*.zip
            upload/*.tar.gz
            upload/checksums.txt
